spring:
  application:
    name: student-service

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: <your-machine-ip>

#jwt:
#  secret: your_secret_key
