server:
  port: 8761

eureka:
  instance:
    hostname: <eureka-server-ip>
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
